server:
  port: 9091
  servlet:
    context-path: /discovery-service

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: discovery-service
  output:
    ansi:
      enabled: always
  config:
    enabled: false
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
management:
  tracing:
    sampling:
      probability: 1.0