- name: Create sysconfig directory
  file:
    path: /etc/sysconfig
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
  become_user: root

- name: Create environment file
  template:
    src: "environment.j2"
    dest: "/etc/sysconfig/{{ site }}"
    owner: root
    group: root
    mode: '0600'
  become: yes
  become_user: root

- name: Create systemd service file from template
  template:
    src: "systemd_service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  become: yes
  become_user: root  # Ensure root can write

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes
  become_user: root  # Run as root

- name: Enable and start the service
  systemd:
    name: "{{ service_name }}"
    enabled: yes
    state: restarted
  become: yes
  become_user: root  # Run as root
